const languages = [
    { name: "Afrikaans", code: "af" },
  { name: "Amharic", code: "am" },
  { name: "Arabic", code: "ar" },
  { name: "Mapudungun", code: "arn" },
  { name: "Assamese", code: "as" },
  { name: "Azerbaijani", code: "az" },
  { name: "Bashkir", code: "ba" },
  { name: "Belarusian", code: "be" },
  { name: "Bulgarian", code: "bg" },
  { name: "Bengali", code: "bn" },
  { name: "Tibetan", code: "bo" },
  { name: "Breton", code: "br" },
  { name: "Bosnian", code: "bs" },
  { name: "Catalan", code: "ca" },
  { name: "Corsican", code: "co" },
  { name: "Czech", code: "cs" },
  { name: "Welsh", code: "cy" },
  { name: "Danish", code: "da" },
  { name: "German", code: "de" },
  { name: "Lower Sorbian", code: "dsb" },
  { name: "Divehi", code: "dv" },
  { name: "Greek", code: "el" },
  { name: "English", code: "en" },
  { name: "Spanish", code: "es" },
  { name: "Estonian", code: "et" },
  { name: "Basque", code: "eu" },
  { name: "Persian", code: "fa" },
  { name: "Finnish", code: "fi" },
  { name: "Filipino", code: "fil" },
  { name: "Faroese", code: "fo" },
  { name: "French", code: "fr" },
  { name: "Frisian", code: "fy" },
  { name: "Irish", code: "ga" },
  { name: "Scottish Gaelic", code: "gd" },
  { name: "Galician", code: "gl" },
  { name: "Swiss German", code: "gsw" },
  { name: "Gujarati", code: "gu" },
  { name: "Hausa", code: "ha" },
  { name: "Hebrew", code: "he" },
  { name: "Hindi", code: "hi" },
  { name: "Croatian", code: "hr" },
  { name: "Upper Sorbian", code: "hsb" },
  { name: "Hungarian", code: "hu" },
  { name: "Armenian", code: "hy" },
  { name: "Indonesian", code: "id" },
  { name: "Igbo", code: "ig" },
  { name: "Yi", code: "ii" },
  { name: "Icelandic", code: "is" },
  { name: "Italian", code: "it" },
  { name: "Inuktitut", code: "iu" },
  { name: "Japanese", code: "ja" },
  { name: "Georgian", code: "ka" },
  { name: "Kazakh", code: "kk" },
  { name: "Greenlandic", code: "kl" },
  { name: "Khmer", code: "km" },
  { name: "Kannada", code: "kn" },
  { name: "Korean", code: "ko" },
  { name: "Konkani", code: "kok" },
  { name: "Kurdi", code: "ckb" },
  { name: "Kyrgyz", code: "ky" },
  { name: "Luxembourgish", code: "lb" },
  { name: "Lao", code: "lo" },
  { name: "Lithuanian", code: "lt" },
  { name: "Latvian", code: "lv" },
  { name: "Maori", code: "mi" },
  { name: "Macedonian", code: "mk" },
  { name: "Malayalam", code: "ml" },
  { name: "Mongolian", code: "mn" },
  { name: "Mohawk", code: "moh" },
  { name: "Marathi", code: "mr" },
  { name: "Malay", code: "ms" },
  { name: "Maltese", code: "mt" },
  { name: "Burmese", code: "my" },
  { name: "Norwegian (Bokmål)", code: "nb" },
  { name: "Nepali", code: "ne" },
  { name: "Dutch", code: "nl" },
  { name: "Norwegian (Nynorsk)", code: "nn" },
  { name: "Norwegian", code: "no" },
  { name: "Sesotho", code: "st" },
  { name: "Occitan", code: "oc" },
  { name: "Odia", code: "or" },
  { name: "Punjabi", code: "pa" },
  { name: "Polish", code: "pl" },
  { name: "Dari", code: "prs" },
  { name: "Pashto", code: "ps" },
  { name: "Portuguese", code: "pt" },
  { name: "K'iche", code: "quc" },
  { name: "Quechua", code: "qu" },
  { name: "Romansh", code: "rm" },
  { name: "Romanian", code: "ro" },
  { name: "Russian", code: "ru" },
  { name: "Kinyarwanda", code: "rw" },
  { name: "Sanskrit", code: "sa" },
  { name: "Yakut", code: "sah" },
  { name: "Sami (Northern)", code: "se" },
  { name: "Sinhala", code: "si" },
  { name: "Slovak", code: "sk" },
  { name: "Slovenian", code: "sl" },
  { name: "Sami (Southern)", code: "sma" },
  { name: "Sami (Lule)", code: "smj" },
  { name: "Sami (Inari)", code: "smn" },
  { name: "Sami (Skolt)", code: "sms" },
  { name: "Albanian", code: "sq" },
  { name: "Serbian", code: "sr" },
  { name: "Swedish", code: "sv" },
  { name: "Kiswahili", code: "sw" },
  { name: "Syriac", code: "syc" },
  { name: "Tamil", code: "ta" },
  { name: "Telugu", code: "te" },
  { name: 'Tajik', code: 'tg' },
  { name: 'Thai', code: 'th' },
  { name: 'Turkmen', code: 'tk' },
  { name: 'Tswana', code: 'tn' },
  { name: 'Turkish', code: 'tr' },
  { name: 'Tatar', code: 'tt' },
  { name: 'Tamazight', code: 'tzm' },
  { name: 'Uyghur', code: 'ug' },
  { name: 'Ukrainian', code: 'uk' },
  { name: 'Urdu', code: 'ur' },
  { name: 'Uzbek', code: 'uz' },
  { name: 'Vietnamese', code: 'vi' },
  { name: 'Wolof', code: 'wo' },
  { name: 'Xhosa', code: 'xh' },
  { name: 'Yoruba', code: 'yo' },
  { name: 'Chinese', code: 'zh' },
  { name: 'Zulu', code: 'zu' }
];
  
  export default languages;
  